### ISSUE TITLE
Does this plugin work with ssm references outside of the "environment" block?

### ISSUE THREAD

**Issue by kevinswarner** [janders223/serverless-offline-ssm#11]
It appears that ssm references outside of the "environment" block (e.g. in the custom variables block) do not get assigned.

```
## serverless.yml file

service: foobar

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}

  environment:
    FOO: ${ssm:foo}

custom:
  BAR: ${ssm:bar}

plugins:
  - serverless-offline-ssm
  - serverless-offline

...
```

```
# .env file

FOO=1
BAR=2
```

In the example above, I get two warnings, which I expect...

A valid SSM parameter to satisfy the declaration 'ssm:foo' could not be found.
A valid SSM parameter to satisfy the declaration 'ssm:bar' could not be found.

But I only get one message about setting a variable...

Serverless: Setting 'Service' Variable FOO to 1

I would expect the following as well...

Serverless: Setting 'Service' Variable BAR to 2

Is this not supported? Or maybe I am doing something incorrectly. Thanks!
