### ISSUE TITLE
Offline SSM parameter on a different region

### ISSUE THREAD

**Issue by vuk** [janders223/serverless-offline-ssm#222]
Is it possible to set offline parameters for different regions to one set in serverless.yml file? 

For instance: 

```
provider: 
  region: eu-west-1
```

and then somewhere down the line I have something like 

``` 
custom: 
   variable: ${ssm(us-east-1):/some/ssm/parameter}
```

If I do something like this: 

```
custom: 
  serverless-offline-ssm:
    stages:
      - offline
    ssm:
      '/some/ssm/parameter': 'some-value'
      # or this 
      'us-east-1:/some/ssm/parameter': 'some-value'
```

this doesn't work. So is there a way to define an SSM parameter in a different region?
