### ISSUE TITLE
Serverless 3 Breaking Change?

### ISSUE THREAD

**Issue by jdesrochers** [janders223/serverless-offline-ssm#255]
The serverless-offline-ssm works fine with Serverless 2.  However, it doesn't seem to work with Serverless 3.  The following serverless.yml has the important snippets for the problem that we are seeing.  This works with version 2 but not 3.
```
plugins:
  - serverless-offline-ssm
  - serverless-offline

custom
  stages:
    - local
    - dev
    - staging
    - production
  myTest:
    local: 'local value'
    dev: ${ssm:DEVELOPMENT.MY_TEST}
    staging: ${ssm:STAGING.MY_TEST}
    production: ${ssm:PRODUCTION.MY_TEST}
  serverless-offline-ssm:
    stages:
      - local
    ssm:
      'DEVELOPMENT.MY_TEST': 'dev value'
      'STAGING.MY_TEST': 'staging value'
      'PRODUCTION.MY_TEST': 'production value'
```
To start we use the following
```
sls offline -s local
```
Then we get this error
```
TypeError: Cannot read property 'find' of undefined
    at new ServerlessOfflineSSM (.../node_modules/serverless-offline-ssm/dist/index.js:57:18)
    at PluginManager.addPlugin (.../node_modules/serverless/lib/classes/plugin-manager.js:88:28)
    at .../node_modules/serverless/lib/classes/plugin-manager.js:134:69
    at Array.forEach (<anonymous>)
    at PluginManager.loadAllPlugins (.../node_modules/serverless/lib/classes/plugin-manager.js:134:44)
    at async Serverless.init (.../node_modules/serverless/lib/serverless.js:137:5)
    at async .../node_modules/serverless/scripts/serverless.js:530:7
```
Line 57 has the following
```
            this.ssmResolver = serverless.variables.variableResolvers
                .find(({ serviceName }) => serviceName === 'SSM');
```
The issue is that variableResolvers doesn't seem to exist in serverless 3.  This works fine with serverless 2.  Have not been able to find what the exact change was in serverless 3 or I would have looked at a PR option.
