### ISSUE TITLE
Does not play well with serverless-dynamodb-local

### ISSUE THREAD

**Issue by kpeters-cbsi** [janders223/serverless-offline-ssm#29]
With this plugin enabled, executing `sls dynamodb install` (as per the plugin instructions) fails with the message `The plugin "serverless-offline-ssm" only runs when offline.`. A snippet of my serverless.yml:

```
plugins:
  - serverless-offline-ssm # simulate SSM locally for testing
  - serverless-plugin-custom-roles
  - serverless-webpack
  - serverless-s3-local # Simulate S3 locally for testing
  - serverless-dynamodb-local # Simulate DynamoDB locally for testing
  - serverless-offline # Execute lambdas locally for testing

custom:
  stage: ${opt:stage, dev}
  tableName: ${ssm:/xxxx/config/table_name}
  bucketName: ${ssm:/xxxx/config/bucket_name}
  topicName: ${ssm:/xxxx/config/topic_name}
  listenerArn: ${ssm:/xxxx/config/listener_arn~true}
  dynamodb:
    stages:
      - dev
    start:
      inMemory: true
      migrate: true
  s3:
    directory: /tmp/s3-local
```
