### ISSUE TITLE
Failing to find .env with serverless v1.70.1

### ISSUE THREAD

**Issue by alexb-uk** [janders223/serverless-offline-ssm#31]
Hi,

I've tried updating to the latest versions of `serverless` and `serverless-offline-ssm` but it appears that `serverless 1.70.1` is causing `.env` to no longer be picked up.

Works:
```yaml
"serverless": "^1.67.3",
"serverless-offline": "^6.1.5",
"serverless-offline-sns": "^0.68.0",
"serverless-offline-ssm": "^4.1.2",
"serverless-plugin-tracing": "^2.0.0",
"serverless-webpack": "^5.3.2",
```

Does not pick up `.env`:

```
 Serverless Warning --------------------------------------

  A valid SSM parameter to satisfy the declaration 'ssm:/xxx/yyy/zzz' could not be found.
```

```yaml
"serverless": "^1.70.1",
"serverless-offline": "^6.1.5",
"serverless-offline-sns": "^0.68.0",
"serverless-offline-ssm": "^4.1.2",
"serverless-plugin-tracing": "^2.0.0",
"serverless-webpack": "^5.3.2",
```

Cut down serverless.yml:
```yaml
provider:
  environment:
    DB_READ_HOST: ${ssm:/${self:provider.stage}/database/read_host}

custom:
  serverless-offline-ssm:
    stages:
        - dev
```

```yaml
"serverless": "^1.70.1",
"serverless-offline": "^6.1.5",
"serverless-offline-sns": "^0.68.0",
"serverless-offline-ssm": "^4.1.2",
"serverless-plugin-tracing": "^2.0.0",
"serverless-webpack": "^5.3.2",
```

Thanks for all you efforts on this library if there's anything I can look into further or provide you with more info please don't hesistate to ask.

Alex
