### ISSUE TITLE
Trying to populate non string value into a string for variable 

### ISSUE THREAD

**Issue by gcphost** [janders223/serverless-offline-ssm#5]
Hi

I am trying to use ssm variables for my iam roles, example:
```
  iamRoleStatements:
  - Effect: Allow
    Action:
      - s3:*
    Resource: 
      - "arn:aws:s3:::${ssm:/${self:custom.stage}/A_BUCKET}/*"
```

This results in the error:
> Trying to populate non string value into a string for variable ${ssm:/local/A_BUCKET}. Please make sure the value of the property is a string.

If I edit the error message in serverless I can see the problem is my variable is `undefined` and not a string:
>  ServerlessError: Trying to populate non string value into a string for variable ${ssm:/local/A_BUCKET} undefined. Please make sure the value of the property is a string.

Since the variable is defined in my environment I assumed it would work.

I am not certain if the issue is related to this plugin or should be directed to serverless itself.

Thanks for the plugin and any support given.

<3 serverless
