### ISSUE TITLE
Not reading in the env variables

### ISSUE THREAD

**Issue by shavo007** [janders223/serverless-offline-ssm#7]
Hi,

I have env variables using ssm, when i run locally using serverless-offline i get an exception 

```
ServerlessError: null
    at serverless.getProvider.request.then.catch (node_modules/serverless/lib/classes/Variables.js:696:35)
From previous event:
    at Variables.getValueFromSsm (node_modules/serverless/lib/classes/Variables.js:693:13)
    at Variables.getValueFromSource (node_modules/serverless/lib/classes/Variables.js:484:20)
    at Variables.splitAndGet (node_modules/serverless/lib/classes/Variables.js:366:17)

```

Serverless.yml 

```

plugins:
  - serverless-webpack # Use serverless-webpack plugin to transpile ES6/ES7
  - serverless-offline-ssm
  - serverless-offline
  - serverless-apigw-binary
  - serverless-domain-manager
  - serverless-plugin-warmup

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-southeast-2
  cfLogs: true
  environment:
        STAGE: ${opt:stage}
        INVOICE_SERVICE_AUTH: ${ssm:/${self:custom.stage/invoice_service_basic_auth~true}
        INVOICE_SERVICE_API_KEY: ${ssm:/${self:custom.stage}/invoice_service_api_key~true}

```

.env

```
INVOICE_SERVICE_AUTH=REDACTED
INVOICE_SERVICE_API_KEY=REDACTED
```

package.json

```
"start:mock-api": "cross-env DEBUG=express:* nodemon ./mock-api/",
        "start:api": "SLS_DEBUG=* serverless offline start --stage local --noAuth",
        "serve": "npm-run-all -p start:mock-api start:api",
```

What am i missing!?

**Comment by janders223** [comment]
Your ssm parameters and environment variables in `.env` file should match. So your `.env` should look as such:
```
invoice_service_basic_auth=foo
invoice_service_api=bar
```

**Comment by shavo007** [comment]
ok, i made that change now and i get the warning 

```
 Serverless Warning --------------------------------------

  A valid SSM parameter to satisfy the declaration 'ssm:/local/invoice_service_api_key~true' could not be found.

```

is that expected?

**Comment by janders223** [comment]
Unfortunately the way serverless loads plugins causes this.

**Comment by ricxsar** [comment]
Hi. I also experiencing this issue. I'm adding debug logs to source code:
```
const updateEnvironment = (provider, lines, serverless, debugName) => {
  const { environment } = provider;

  console.log("environment:", environment);
  console.log("lines:", lines);

  Object.keys(environment || {}).forEach(key => {
    if (checkParam(environment[key])) {

      lines.forEach(line => {
        const [envKey, value] = line.split(/=(.*)/);

        if (envKey === key) {
          serverless.cli.log(`Setting '${debugName}' Variable ${key} to ${value}`);

          environment[key] = value;
        }
      });
    }
  });

  const updatedProvider = provider;
  updatedProvider.environment = environment;
  return updatedProvider
};
```
It returns resolve ssm value from AWS not the value specified by the `serverless.yml` file not `${ssm:${opt:stage, self:provider.stage}_redis_host}` and `${ssm:${opt:stage, self:provider.stage}_redis_port}` so the environment variables are not replaced.
```
environment: {
  NODE_ENV: 'dev',
  REDIS_HOST: 'sample host',
  REDIS_PORT: '6379' }
lines: [ 'REDIS_HOST=localhost', 'REDIS_PORT=6379' ]
```
serverless.yml file partial contents:
```
provider:
  environment:
    NODE_ENV: ${opt:stage, self:provider.stage}
    REDIS_HOST: ${ssm:${opt:stage, self:provider.stage}_redis_host}
    REDIS_PORT: ${ssm:${opt:stage, self:provider.stage}_redis_port}
```

I know this is the problem from the serverless itself not in your plugin.

I hope you can suggest to serverless team to allow raw values  from the `serverless.yml` to be accessed so that this plugin will work.
